version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - '8080:80'

  server:
    build: ./server
    ports:
      - '5000:5000'
    environment:
      - APP_ENV=Development
